# Server
source: "site"
#destination: ./_gh_pages
host: "localhost"
port: 4000
baseurl: ""
url: "https://wecaredata.github.io"
encoding: UTF-8
timezone: Asia/Shanghai

# Site
title: up.Smart
description: Connect digital dental world.
organization: WeCareData
author: James Sean
email: james.sean.pro@gmail.com
lang: zh_CN
logo: /logo-robotcaradata.svg

# Theme
#theme: jekyll-theme-robotcaredata

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - docs/4.4/assets/scss

# Dependencies
markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

# Permalinks
permalink: pretty

# Plugins
Plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-seo-tag

# Plugins - TOC Settings
min_level: 2
max_level: 4
no_toc_selection_class:
  - "bd-callout"
  - "bd-example"

# Version Control
version_aligner: 1.0.0
version_design_language: 1.0.0
