## Jekyll Settings
source: .
destination: ./_site
#collections_dir: .
plugins_dir: _plugins
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes
sass:
  sass_dir: ./_sass
collections:
  posts:
    output: true

# Handling Reading
safe: false
#include: [".htaccess"]
exclude: ["Gemfile", "Gemfile.lock", "node_modules","README.md",".gitignore","LICENSE","CNAME"]
keep_files: [".git", ".svn"]
encoding: utf-8
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: false
limit_posts: 0
future: false
unpublished: false
profile: true

# Plugins
whitelist: []
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
#  - jekyll-autoprefixer
#  - jekyll-sass-converter
#  - jemoji
#  - jekyll-toc
#  - jekyll-seo-tag
#  - jekyll-mermaid
#  - jekyll-admin
#  - jekyll-data

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Serving
detach: false
livereload: true
port: 4000
host: localhost
baseurl: ""
url: "https://james-sean.gitee.io"
show_dir_listing: false

# Outputting
permalink: pretty
timezone: Asia/Shanghai

quiet: false
verbose: false
defaults: []

liquid:
  strict_variables: false
  strict_filters: false

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  show_warnings: true

# Site
title: 3D打印平台
description: Connect digital dental world
organization: WHUSS
author: WHUSS
email: info@whuss.com
lang: zh_CN

## Plugins Settings
# jekyll-toc

redirect_from:
  json: false

paginate: 10
paginate_path: "blog/page:num"

# Custom variables
assets:
  css:              "/assets/css/"
  js:               "/assets/js/"
  images:           "/assets/images/"
