- title: "融合"
  description: "最大限度融合各平台常用数据格式<br>实现医生-患者-技工三方的融合"
  thumb: home-services-01
- title: "权威"
  description: "由知名专家审核把关"
  thumb: home-services-02
- title: "快速"
  description: "实现3D打印修复体的快速制作"
  thumb: home-services-03
- title: "高效"
  description: "一体化平台减少沟通及物流成本，提高制作效率"
  thumb: home-services-04
