aligner:
  - group: v1.x
    baseurl: https://wecaradata.github.io
    versions:
      - version: 1.0.0
upcera:
  - group: v1.x
    baseurl: https://wecaradata.github.io
    versions:
      - version: 1.0.0
